"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class FloatMultiArray(object):
    __slots__ = ["size", "data"]

    __typenames__ = ["int16_t", "float"]

    __dimensions__ = [None, ["size"]]

    def __init__(self):
        self.size = 0
        self.data = []

    def encode(self):
        buf = BytesIO()
        buf.write(FloatMultiArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.size))
        buf.write(struct.pack('>%df' % self.size, *self.data[:self.size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != FloatMultiArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return FloatMultiArray._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = FloatMultiArray()
        self.size = struct.unpack(">h", buf.read(2))[0]
        self.data = struct.unpack('>%df' % self.size, buf.read(self.size * 4))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if FloatMultiArray in parents: return 0
        tmphash = (0xd449e6603ebed71c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if FloatMultiArray._packed_fingerprint is None:
            FloatMultiArray._packed_fingerprint = struct.pack(">Q", FloatMultiArray._get_hash_recursive([]))
        return FloatMultiArray._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", FloatMultiArray._get_packed_fingerprint())[0]
