"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Float32MultiArray(object):

    __slots__ = ["size", "data"]

    __typenames__ = ["int16_t", "float"]

    __dimensions__ = [None, ["size"]]

    def __init__(self):
        self.size = 0
        """ LCM Type: int16_t """
        self.data = []
        """ LCM Type: float[size] """

    def encode(self):
        buf = BytesIO()
        buf.write(Float32MultiArray._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.size))
        buf.write(struct.pack('>%df' % self.size, *self.data[:self.size]))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Float32MultiArray._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Float32MultiArray._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Float32MultiArray()
        self.size = struct.unpack(">h", buf.read(2))[0]
        self.data = struct.unpack('>%df' % self.size, buf.read(self.size * 4))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Float32MultiArray in parents: return 0
        tmphash = (0xd449e6603ebed71c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Float32MultiArray._packed_fingerprint is None:
            Float32MultiArray._packed_fingerprint = struct.pack(">Q", Float32MultiArray._get_hash_recursive([]))
        return Float32MultiArray._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Float32MultiArray._get_packed_fingerprint())[0]

