"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class Orientation(object):

    __slots__ = ["x", "y", "z", "w"]

    __typenames__ = ["float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.x = 0.0
        """ LCM Type: float """
        self.y = 0.0
        """ LCM Type: float """
        self.z = 0.0
        """ LCM Type: float """
        self.w = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(Orientation._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">ffff", self.x, self.y, self.z, self.w))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Orientation._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Orientation._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Orientation()
        self.x, self.y, self.z, self.w = struct.unpack(">ffff", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Orientation in parents: return 0
        tmphash = (0xa019400fc7475bab) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Orientation._packed_fingerprint is None:
            Orientation._packed_fingerprint = struct.pack(">Q", Orientation._get_hash_recursive([]))
        return Orientation._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Orientation._get_packed_fingerprint())[0]

