"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

from components.lcm_msg import lcm_std

class Twist(object):

    __slots__ = ["linear", "angular"]

    __typenames__ = ["lcm_std.Vector3", "lcm_std.Vector3"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.linear = lcm_std.Vector3()
        """ LCM Type: lcm_std.Vector3 """
        self.angular = lcm_std.Vector3()
        """ LCM Type: lcm_std.Vector3 """

    def encode(self):
        buf = BytesIO()
        buf.write(Twist._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.linear._get_packed_fingerprint() == lcm_std.Vector3._get_packed_fingerprint()
        self.linear._encode_one(buf)
        assert self.angular._get_packed_fingerprint() == lcm_std.Vector3._get_packed_fingerprint()
        self.angular._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != Twist._get_packed_fingerprint():
            raise ValueError("Decode error")
        return Twist._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = Twist()
        self.linear = lcm_std.Vector3._decode_one(buf)
        self.angular = lcm_std.Vector3._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if Twist in parents: return 0
        newparents = parents + [Twist]
        tmphash = (0x3a4144772922add7+ lcm_std.Vector3._get_hash_recursive(newparents)+ lcm_std.Vector3._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if Twist._packed_fingerprint is None:
            Twist._packed_fingerprint = struct.pack(">Q", Twist._get_hash_recursive([]))
        return Twist._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", Twist._get_packed_fingerprint())[0]

